# Generated by Django 6.0.1 on 2026-02-12 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('annual', 'Annual Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('unpaid', 'Unpaid Leave'), ('compensatory', 'Compensatory Off'), ('emergency', 'Emergency Leave'), ('other', 'Other')], default='casual', help_text='Type of leave being requested', max_length=20)),
                ('from_date', models.DateField(help_text='Start date of leave')),
                ('to_date', models.DateField(help_text='End date of leave')),
                ('total_days', models.IntegerField(blank=True, help_text='Total number of leave days (auto-calculated)', null=True)),
                ('reason', models.TextField(help_text='Reason for leave request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of leave request', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, help_text='Date when request was approved/rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('attachment', models.CharField(blank=True, help_text='Path to supporting document (medical certificate, etc.)', max_length=255, null=True)),
                ('comments', models.TextField(blank=True, help_text='Additional comments from approver', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approvedById', help_text='User who approved/rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='user.user')),
                ('approver', models.ForeignKey(blank=True, db_column='approverId', help_text='User who can approve/reject this request (HR/Admin/Manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to='user.user')),
                ('employee', models.ForeignKey(blank=True, db_column='employeeId', help_text='Employee record of the user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='user.employee')),
                ('user', models.ForeignKey(db_column='userId', help_text='User requesting the leave', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='user.user')),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='leave_reque_userId_4ced43_idx'), models.Index(fields=['approver', 'status'], name='leave_reque_approve_1ac9d7_idx'), models.Index(fields=['from_date', 'to_date'], name='leave_reque_from_da_f8fc81_idx')],
            },
        ),
    ]
